# Generated by Django 3.2.6 on 2021-08-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_historicaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldocument',
            name='field_changed',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
